#
# Makefile.bor,v 1.1 2002/07/27 13:08:43 jwillemsen Exp
# Makefile for building the svcconf example
#

NAME = Svcconf

OBJFILES = \
        $(OBJDIR)\Svcconf_Handler.obj \
	$(OBJDIR)\main.obj

CFLAGS = \
	$(ACE_CFLAGS) \
	$(ACE_XML_CFLAGS) \
	$(ACE_XML_PARSER_CFLAGS)

CPPDIR = .

LIBFILES = \
	$(ACE_LIB) \
	$(ACE_XML_LIB) \
	$(ACE_XML_PARSER_LIB)

!include <$(ACE_ROOT)\include\makeinclude\build_exe.bor>
