# Makefile,v 1.2 2003/10/05 22:37:27 shuston Exp
#
# Copyright 2003 Addison-Wesley Inc. All Rights Reserved.

BIN =	Process_Manager_Death \
	Process_Manager_Spawn \
	Process_Mutex \
	Spawn

SOURCES = $(addsuffix .cpp,$(BIN))

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
