#if !defined(AFX_WEBBROWSER2_H__5B71CD96_5943_44BE_A475_92E58F26600C__INCLUDED_)
#define AFX_WEBBROWSER2_H__5B71CD96_5943_44BE_A475_92E58F26600C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.



// IDocHostUIHandler와 DOCHOSTUIINFO 구조체를 사용하기 위한 헤더 파일
#include <mshtmhst.h>


/////////////////////////////////////////////////////////////////////////////
// CWebBrowser2 wrapper class
// 옵션 설정이 가능한 웹브라우저 컨트롤 클래스
class CWebBrowser2 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CWebBrowser2)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8856f961, 0x340a, 0x11d0, { 0xa9, 0x6b, 0x0, 0xc0, 0x4f, 0xd7, 0x5, 0xa2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	// 멤버 변수들을 추가한다
	BOOL		m_bContextMenu;			// 컨텍스트 메뉴 사용 여부
	BOOL		m_bNo3DBorder;			// 3D 테두리 출력 여부
	BOOL		m_bNoScrollBar;			// 스크롤바 출력 여부
	BOOL		m_bFlatScrollBar;		// 평면 스크롤바 사용 여부

	CRgn		m_rgnBitmap;			// 비트맵에서 추출한 영역을 저장하는 변수

	// 웹브라우저 모양 변경에 사용할 비트맵을 설정하는 함수 : 파일에서 읽기
	void SetShapeBitmap(LPCTSTR pFileName, COLORREF clrTransparent);
	// 웹브라우저 모양 변경에 사용할 비트맵을 설정하는 함수 : 로드된 리소스를 설정
	void SetShapeBitmap(HBITMAP hBitmap, COLORREF clrTransparent);


// Operations
public:
	CWebBrowser2();
	virtual ~CWebBrowser2();

	// 웹브라우저의 속성 변경이 가능하도록 CCustomControlSite에서 호출해주는 함수
	// 웹브라우저 컨트롤의 UI 속성을 변경할 수 있도록 호출되는 함수
	HRESULT OnGetHostInfo(DOCHOSTUIINFO *pInfo);
	// 웹브라우저 컨트롤에서 컨텍스트 메뉴 출력이 필요할 때 호출되는 함수
	HRESULT OnShowContextMenu();

	void GoBack();
	void GoForward();
	void GoHome();
	void GoSearch();
	void Navigate(LPCTSTR URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers);
	void Refresh();
	void Refresh2(VARIANT* Level);
	void Stop();
	LPDISPATCH GetApplication();
	LPDISPATCH GetParent();
	LPDISPATCH GetContainer();
	LPDISPATCH GetDocument();
	BOOL GetTopLevelContainer();
	CString GetType();
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	CString GetLocationName();
	CString GetLocationURL();
	BOOL GetBusy();
	void Quit();
	void ClientToWindow(long* pcx, long* pcy);
	void PutProperty(LPCTSTR Property_, const VARIANT& vtValue);
	VARIANT GetProperty_(LPCTSTR Property_);
	CString GetName();
	long GetHwnd();
	CString GetFullName();
	CString GetPath();
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetStatusBar();
	void SetStatusBar(BOOL bNewValue);
	CString GetStatusText();
	void SetStatusText(LPCTSTR lpszNewValue);
	long GetToolBar();
	void SetToolBar(long nNewValue);
	BOOL GetMenuBar();
	void SetMenuBar(BOOL bNewValue);
	BOOL GetFullScreen();
	void SetFullScreen(BOOL bNewValue);
	void Navigate2(VARIANT* URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers);
	long QueryStatusWB(long cmdID);
	void ExecWB(long cmdID, long cmdexecopt, VARIANT* pvaIn, VARIANT* pvaOut);
	void ShowBrowserBar(VARIANT* pvaClsid, VARIANT* pvarShow, VARIANT* pvarSize);
	long GetReadyState();
	BOOL GetOffline();
	void SetOffline(BOOL bNewValue);
	BOOL GetSilent();
	void SetSilent(BOOL bNewValue);
	BOOL GetRegisterAsBrowser();
	void SetRegisterAsBrowser(BOOL bNewValue);
	BOOL GetRegisterAsDropTarget();
	void SetRegisterAsDropTarget(BOOL bNewValue);
	BOOL GetTheaterMode();
	void SetTheaterMode(BOOL bNewValue);
	BOOL GetAddressBar();
	void SetAddressBar(BOOL bNewValue);
	BOOL GetResizable();
	void SetResizable(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WEBBROWSER2_H__5B71CD96_5943_44BE_A475_92E58F26600C__INCLUDED_)
