# Makefile,v 1.2 2003/10/02 02:59:32 shuston Exp
#
# Copyright 2003 Addison-Wesley Inc. All Rights Reserved.
# Makefile for Reactor-based examples

BIN =	Client \
	HAStatus \
	HAStatus-AC \
	Reschedule \
	Schedule_Timers \
	Timer_Cancel \
	Timers \
	Timer_State_Data

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
