# Makefile,v 1.1 2003/10/07 20:55:05 shuston Exp
#
# Copyright 2003 Addison-Wesley Inc. All Rights Reserved.

BIN =	Futures \
	LF_ThreadPool \
	Task_ThreadPool \
	ThreadPool \
	TP_Reactor

SOURCES = $(addsuffix .cpp,$(BIN))

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
