# Makefile,v 1.1 2003/10/09 17:38:27 shuston Exp
#
# Copyright 2003 Addison-Wesley Inc. All Rights Reserved.

BIN = Hash_Map Malloc Mem_Map PI_Malloc Pool_Growth

SOURCES = $(addsuffix .cpp,$(BIN))

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
