# Makefile,v 1.1 2003/10/06 21:08:18 shuston Exp
#
# Copyright 2003 Addison-Wesley Inc. All Rights Reserved.

BIN =	Async_Cancel \
	Coop_Cancel \
	ExitHandler \
	Pool \
	Priorities \
	Signals \
	Signals2 \
	Start_Hook \
	State

SOURCES = $(addsuffix .cpp,$(BIN))

include $(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU
include $(ACE_ROOT)/include/makeinclude/macros.GNU
include $(ACE_ROOT)/include/makeinclude/rules.common.GNU
include $(ACE_ROOT)/include/makeinclude/rules.nonested.GNU
include $(ACE_ROOT)/include/makeinclude/rules.bin.GNU
include $(ACE_ROOT)/include/makeinclude/rules.local.GNU
