#----------------------------------------------------------------------------
#	Makefile,v 1.14 2003/10/09 17:38:11 shuston Exp
#
#	Makefile for the ACE examples/APG directory
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------

DIRS  =	Active_Objects \
	Config \
	Containers \
	Logging \
	Misc_IPC \
	Naming \
	Proactor \
	Processes \
	Reactor \
	Shared_Memory \
	Signals \
	Sockets \
	Streams \
	Svc_Config \
	Threads \
	ThreadManagement \
	ThreadPools \
	ThreadSafety \
	Timers

#----------------------------------------------------------------------------
#	Include macros and targets
#----------------------------------------------------------------------------

include	$(ACE_ROOT)/include/makeinclude/wrapper_macros.GNU

include	$(ACE_ROOT)/include/makeinclude/macros.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.common.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.nested.GNU
include	$(ACE_ROOT)/include/makeinclude/rules.nolocal.GNU
